name: wce_notice_board
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# last known good working repository:
#       Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
#       Framework • revision 7e9793dee1 (9 weeks ago) • 2022-03-02 11:23:12 -0600
#       Engine • revision bd539267b4
#       Tools • Dart 2.16.1 • DevTools 2.9.2
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  date_range_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.4
  firebase_auth: ^3.3.2
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^3.1.5
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  file_picker: ^4.3.3
  path: ^1.8.0
  firebase_storage: ^10.2.9
  country_pickers: ^2.0.0
  flutter_document_picker: ^4.0.1
  connectivity_plus: ^2.2.1
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^8.3.0
  dio: ^4.0.4
  flutter_local_notifications: ^9.4.0
  blurry: ^1.0.0
  shared_preferences: ^2.0.8
  string_validator: ^0.3.0
  image_picker: ^0.8.4+1
  email_validator: ^2.0.1
  path_provider: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
